name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '424.0.0'
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        project_id: ncaambb-443717
        
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        registry: us-west1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON  }}
      
    - name: Configure Docker authentication
      run: gcloud auth configure-docker us-west1-docker.pkg.dev


    - name: Build and push Docker image
      run: |
        IMAGE_NAME="us-west1-docker.pkg.dev/ncaambb-443717/cloud-run-source-deploy/ncaa-predict/ncaa-predict:46df0c71094feb8e7003678e189343351734f37c"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
        
    - name: Github Actions Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: 'ncaa-predict'
        image: "us-west1-docker.pkg.dev/ncaambb-443717/cloud-run-source-deploy/ncaa-predict/ncaa-predict:46df0c71094feb8e7003678e189343351734f37c"
        
        # NOTE: If using a pre-built image, update the image name here
        # image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
        # NOTE: You can also set env variables here:

    # - name: Deploy to Cloud Run
    #   run: |
    #     IMAGE_NAME="us-west1-docker.pkg.dev/ncaambb-443717/cloud-run-source-deploy/ncaa-predict/ncaa-predict:46df0c71094feb8e7003678e189343351734f37c"
    #     gcloud run deploy ncaambb-app \
    #       --image $IMAGE_NAME \
    #       --platform managed \
    #       --region us-west1 \
    #       --allow-unauthenticated \
    #       --service-account cloud-run-sa@ncaambb-443717.iam.gserviceaccount.com
