name: Monitoring Check

on:
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  check-monitoring:
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

    - name: Query Monitoring Data
      run: |
        gcloud monitoring metrics list \
          --filter="metric.type=starts_with('appengine.googleapis.com')"
